spring:
  application:
    name:
      spring-security-basics

  datasource:
    url: jdbc:postgresql://localhost:5432/ssb
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true